# Generated by Django 2.2 on 2019-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190515_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='u', max_length=70),
            preserve_default=False,
        ),
    ]
