# Generated by Django 2.2 on 2019-05-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190522_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.ImageField(default='users/not-user.png', upload_to='users/'),
        ),
    ]
