# Generated by Django 2.2.1 on 2019-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20190528_1608'),
        ('users', '0007_auto_20190522_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savedRecipes',
            field=models.ManyToManyField(to='recipe.Recipe'),
        ),
    ]
