# Generated by Django 2.2 on 2019-04-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImage', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('difficulty', models.DecimalField(decimal_places=0, max_digits=1)),
                ('prepTime', models.DecimalField(decimal_places=0, max_digits=3)),
                ('cookTime', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ingredients', models.TextField(max_length=600)),
                ('portions', models.CharField(max_length=40)),
                ('shared', models.BooleanField(default=False)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
