# Generated by Django 2.2.1 on 2019-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
