# Generated by Django 2.2.1 on 2019-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20190515_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
