# Generated by Django 2.2.1 on 2019-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20190519_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mainImage',
            field=models.ImageField(upload_to='recipes/titleImgs/'),
        ),
    ]
