# Generated by Django 2.2.1 on 2019-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
