# Generated by Django 2.2.1 on 2019-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_step_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='img1',
            field=models.ImageField(upload_to='recipes/steps/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='img2',
            field=models.ImageField(upload_to='recipes/steps/'),
        ),
    ]
