# Generated by Django 2.2.1 on 2019-05-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_auto_20190522_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_set', to='recipe.Recipe'),
        ),
    ]
